### ISSUE TITLE
Real World Case Study

### ISSUE THREAD

**Issue by Stewartarmbrecht** [Azure-Samples/Serverless-Eventing-Platform-for-Microservices#15]
Are there any case studies where this architecture has been used in a production/scaled capacity?  Or are there any implementations where scale and performance have been validated?

I have a group interested in pushing this forward into a reference architecture but wanted to make sure there aren't any gotcha's we will encounter that make the approach unusable (like a periodic 5-10 second response time because of cold start up time for an azure function).

**Comment by nzthiago** [comment]
I've pinged John on twitter who was working hands on with customers on similar solutions, he'll hopefully add more here. Have worked with customers on similar but not 100% exactly the same as this example. 
One gotcha is the SignalR service itself, we haven't done the work to replace [our shim code](https://github.com/Azure-Samples/Serverless-Eventing-Platform-for-Microservices/tree/master/web/src/signalr-web/SignalRMiddleware/SignalRMiddleware) with the actual Azure SignalR service. They way we have it in this sample it won't scale well. 

Another thing to watch out for are concerns that are related to large microservices based solutions in general, like a service registry or a repository of contracts, etc, we didn't go into that here as the main purpose was showcasing Event Grid with custom topics. 

One more thing that comes to mind is being mindful of [dead lettering and retry policies](https://docs.microsoft.com/en-us/azure/event-grid/manage-event-delivery) for Event Grid and having a system to keep track of dead lettered events for mitigation of failed messages. 

Cold start does not come up often in this scenario to be honest, as a production implementation usually has regular usage (and when it doesn't the first hit of cold start is acceptable); but it's something to monitor on your solution, if it becomes a problem it might be worth moving into the more PaaS and less Serverless hosting plans of App Service Plans for Functions.

**Comment by Stewartarmbrecht** [comment]
Thanks Thiago!  This definitely helps.  We will incorporate the items you listed as we move forward.  If you do get more information from John, please add it.  Finally, do you have any recommendations on materials that cover the service registry or contract repository patterns you mentioned above? Specifically, ones that show an Azure implementation.

**Comment by johndowns** [comment]
Hi there, sorry for the delay in replying. I have used parts of this solution in a production (and fairly high-scale) capacity, although not everything.

I have indeed run into cold start issues with HTTP-triggered functions. During quiet periods we found they were put to sleep and then had a longer delay when they started. We solved that with various techniques including having a artificial requests sent regularly to keep the function alive, using an app service plan in conjunction with the `alwaysOn` setting, using precompiled .NET functions, and packaging Node.js functions using gulp.js. Depending on the particular function and its characteristics we selected some of those mitigations to apply. [There is a good article here with more details on how this works and the options available.](https://blogs.msdn.microsoft.com/appserviceteam/2018/02/07/understanding-serverless-cold-start/) As Thiago said, depending on your particular scenario this may not be a big issue.

For **Event Grid custom topics**, I haven't worked with extremely high scale on this and so am not sure whether there may be issues you face, although given the nature of how it works I don't expect there to be problems.

As Thiago mentioned, the **SignalR service** would be one part to look at - Azure SignalR would presumably be a better solution for scale, but we haven't validated that or used it in production.

In terms of the other services used in the sample:
 * **Cognitive Services** should be able to cope with high request volumes but you'd need to upgrade its SKU. I haven't used this in a high-volume production application.
 * **Cosmos DB** can also cope with very high request volumes but you need to pay close attention to partitioning and the request units you allocate - this is a lot more complex than it seems for very high throughput systems (particularly when you're dealing with terabytes of data). [More information is available here](https://docs.microsoft.com/en-us/azure/cosmos-db/partition-data), and I strongly suggest [contacting the Cosmos DB team](https://docs.microsoft.com/en-us/azure/cosmos-db/faq#how-can-i-get-additional-help-with-azure-cosmos-db) early in your project if you plan on having a very high volume of data as they are really helpful with figuring out the best ways to handle this.
 * **Azure Storage** can deal with very high request volumes, but you should check the [quotas](https://docs.microsoft.com/en-us/azure/azure-subscription-service-limits#storage-limits) to confirm they're not going to be an issue for you. Also for storage tables, be very careful choosing partition keys and row keys that 
 * **Application Insights** can deal with very high volumes of data, but be careful as it will charge you for the data it ingests. If you have a lot of logs or metrics published you can run up large bills - [more info is available here](https://docs.microsoft.com/en-us/azure/application-insights/app-insights-pricing), and you can use various approaches including [sampling](https://docs.microsoft.com/en-us/azure/application-insights/app-insights-sampling) to reduce this, or reduce the quota for the App Insights account.

**Comment by Stewartarmbrecht** [comment]
John, thanks for your response.  This is VERY helpful and addresses a lot of concerns from a performance scale perspective.
I had thought about using an azure function to ping other azure functions to avoid the cold start problem.  However, this seemed to go against the grain in terms of what Microsoft would want from a hosting perspective.  If everyone did this, I'm not sure how MS could effectively manage resources and keep overall hosting cost effective.  
Do you have any experience on scaling the model from a development/functional perspective?  What kind of patterns do you need to introduce (or move away from) if you are scaling to 100 or 1000 microservices?  From a handful of teams to 50 or 100?  Thiago mentioned looking into building a service registry or a repository of contracts.  Do you have any references on the best way for doing that?
Thanks!
Stewart

**Comment by johndowns** [comment]
Hi Stewart,

Re using a function to ping another function - yes, it doesn't feel right, and I've found that in situations where I've done that, it's usually been better to switch to an app service plan and turn the `alwaysOn` setting on.

Re scaling - for the particular scenarios I've dealt with I haven't gone as high as 50 or 100 microservices, and I haven't used a service registry for this type of architecture yet either, so I'm afraid I can't point you to any references sorry!

**Comment by Stewartarmbrecht** [comment]
Thanks John!  I appreciate the help!

**Comment by nzthiago** [comment]
Sorry about not getting back earlier @Stewartarmbrecht  - it seems like a discussion for any large microservices architecture; let me find out if others have implemented a service registry and others for their projects where a lot of the microservices were built with Azure Functions, stay tuned

**Comment by irajbalakrish** [comment]
@nzthiago Did you have a chance to pull some details around service registry / repo of contracts

**Comment by nzthiago** [comment]
@irajbalakrish sorry I haven't yet; on Azure there has been more investment in the containers area so far as far as I could find: https://docs.microsoft.com/en-us/dotnet/standard/microservices-architecture/architect-microservice-container-applications/microservices-addressability-service-registry

**Comment by irajbalakrish** [comment]
Hey Thanks @nzthiago !!  I will followup on those content
